<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="lyra mardiana safitri">
<meta name="dcterms.date" content="2024-01-23">

<title>Pengaruh Suhu Udara terhadap Jumlah Wisatawan Bromo Tahun 2000 hingga 2022</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="index.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Pengaruh Suhu Udara terhadap Jumlah Wisatawan Bromo Tahun 2000 hingga 2022</h1>
<p class="subtitle lead">Metode Penelitian Politeknik APP Jakarta</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>lyra mardiana safitri </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 23, 2024</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<p><img src="poltekapp.jpg" class="img-fluid"></p>
<section id="pendahuluan" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="pendahuluan"><span class="header-section-number">1</span> Pendahuluan</h2>
<section id="latar-belakang" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="latar-belakang"><span class="header-section-number">1.1</span> Latar belakang</h3>
<p>Peningkatan suhu udara global telah menjadi perhatian utama dalam beberapa dekade terakhir. Fenomena ini memiliki dampak yang luas, termasuk pada sektor pariwisata. Gunung Bromo, sebagai salah satu destinasi wisata utama di Indonesia, tidak terlepas dari pengaruh suhu udara terhadap jumlah pengunjung. Penelitian ini bertujuan untuk menganalisis bagaimana fluktuasi suhu udara selama periode 2000 hingga 2022 memengaruhi kunjungan wisatawan ke Bromo.</p>
</section>
<section id="ruang-lingkup" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="ruang-lingkup"><span class="header-section-number">1.2</span> Ruang lingkup</h3>
<p>Pada penelitian ini peneliti menggunakan dua variabel yang diambil dari Badan Pusat Statistik kota Malang. Data objek yang digunakan berupa suhu udara dan jumlah wisatawan bromo, dengan data bersifat time series dalam kurun waktu periode tahun 2000 hingga 2022.</p>
</section>
<section id="rumusan-masalah" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="rumusan-masalah"><span class="header-section-number">1.3</span> Rumusan masalah</h3>
<ol type="a">
<li><p>Apakah suhu udara mempengaruhi jumlah wisatawan Bromo ?</p></li>
<li><p>Bagaimana hubungan suhu udara dan jumlah wisatawan Bromo?</p></li>
</ol>
</section>
<section id="tujuan-dan-manfaat-penelitian" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="tujuan-dan-manfaat-penelitian"><span class="header-section-number">1.4</span> Tujuan dan manfaat penelitian</h3>
<p>Tujuan penelitian ini adalah untuk mengetahui seberapa besar pengaruh suhu udara terhadap jumlah wisatawan yang berkunjung ke kawasan wisata Gunung Bromo di Jawa Timur.</p>
<p>Manfaat penelitian ini adalah untuk memberikan informasi yang berguna bagi pihak pengelola wisata, pemerintah, dan masyarakat sekitar tentang faktor-faktor yang memengaruhi minat wisatawan terhadap Gunung Bromo.</p>
</section>
<section id="package" class="level3" data-number="1.5">
<h3 data-number="1.5" class="anchored" data-anchor-id="package"><span class="header-section-number">1.5</span> Package</h3>
<p>Packages yang digunakan antara lain sebagai berikut:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(writexl)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="studi-pustaka" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="studi-pustaka"><span class="header-section-number">2</span> Studi pustaka</h2>
<p>Pengaruh Perubahan Iklim Terhadap Pariwisata: Penelitian sebelumnya telah menyoroti dampak perubahan iklim pada destinasi pariwisata. Analisis ini memberikan kerangka kerja untuk memahami bagaimana suhu udara yang meningkat dapat memengaruhi minat wisatawan.</p>
<p>Pengaruh Suhu Terhadap Aktivitas Wisata Alam: Beberapa studi telah mencoba mengukur dampak suhu terhadap kunjungan wisatawan di area pegunungan dan alam. Temuan-temuan ini dapat memberikan wawasan lebih lanjut tentang pola kunjungan di kawasan Bromo yang terkenal dengan keindahan alamnya.</p>
<p>Analisis Data Kunjungan Wisata Bromo: Meneliti data kunjungan tahunan ke Bromo antara 2000 dan 2022 dapat memberikan pemahaman lebih dalam tentang tren kunjungan. Hal ini mencakup faktor-faktor lain seperti perubahan infrastruktur dan promosi pariwisata yang dapat memengaruhi jumlah pengunjung.</p>
<p>Suhu udara yang terlalu dingin atau terlalu panas dapat mempengaruhi minat wisatawan untuk berkunjung ke tempat wisata tersebut. Berdasarkan penelitian yang dilakukan oleh Nurhayati dan Sari, suhu udara yang ideal untuk berkunjung ke Gunung Bromo adalah antara 10-20 derajat Celsius. Suhu udara yang terlalu dingin atau terlalu panas dapat membuat wisatawan merasa tidak nyaman dan kurang menikmati pengalaman wisata mereka.</p>
<p>Selain itu, penelitian yang dilakukan oleh Kusumawati dan Sari menunjukkan bahwa suhu udara juga mempengaruhi tingkat kunjungan wisatawan ke Gunung Bromo. Mereka menemukan bahwa pada suhu udara yang ideal, jumlah wisatawan yang berkunjung cenderung meningkat. Namun, pada suhu udara yang terlalu dingin atau terlalu panas, jumlah wisatawan cenderung menurun.</p>
<p>Selain suhu udara, faktor lain yang mempengaruhi jumlah wisatawan di Gunung Bromo adalah musim. Menurut penelitian yang dilakukan oleh Sari dan Kusumawati, jumlah wisatawan di Gunung Bromo cenderung meningkat pada musim liburan seperti Natal, Tahun Baru, dan liburan sekolah. Namun, pada musim hujan, jumlah wisatawan cenderung menurun karena kondisi jalan yang licin dan berbahaya.</p>
<p>Dalam kesimpulannya, suhu udara mempengaruhi jumlah wisatawan yang berkunjung ke Gunung Bromo. Suhu udara yang ideal antara 10-20 derajat Celsius dapat meningkatkan minat wisatawan untuk berkunjung ke tempat wisata tersebut. Namun, pada suhu udara yang terlalu dingin atau terlalu panas, jumlah wisatawan cenderung menurun. Selain itu, faktor lain seperti musim juga mempengaruhi jumlah wisatawan di Gunung Bromo.</p>
</section>
<section id="metode-penelitian" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="metode-penelitian"><span class="header-section-number">3</span> Metode penelitian</h2>
<section id="data" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="data"><span class="header-section-number">3.1</span> Data</h3>
<table class="table">
<thead>
<tr class="header">
<th>Tahun</th>
<th>Suhu Udara</th>
<th>wisatawan</th>
<th>x</th>
<th>y</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2000</td>
<td>24.8</td>
<td>75.000</td>
<td>1.394451681</td>
<td>4.875061263</td>
</tr>
<tr class="even">
<td>2001</td>
<td>24,9</td>
<td>80.000</td>
<td>1,396199347</td>
<td>4,903089987</td>
</tr>
<tr class="odd">
<td>2002</td>
<td>25</td>
<td>85.000</td>
<td>1,397940009</td>
<td>4,929418926</td>
</tr>
<tr class="even">
<td>2003</td>
<td>25,1</td>
<td>90.000</td>
<td>1,399673721</td>
<td>4,954242509</td>
</tr>
<tr class="odd">
<td>2004</td>
<td>25,2</td>
<td>95.000</td>
<td>1,401400541</td>
<td>4,977723605</td>
</tr>
<tr class="even">
<td>2005</td>
<td>25,3</td>
<td>100.000</td>
<td>1,403120521</td>
<td>5</td>
</tr>
<tr class="odd">
<td>2006</td>
<td>25,4</td>
<td>105.000</td>
<td>1,404833717</td>
<td>5,021189299</td>
</tr>
<tr class="even">
<td>2007</td>
<td>25,5</td>
<td>110.000</td>
<td>1,40654018</td>
<td>5,041392685</td>
</tr>
<tr class="odd">
<td>2008</td>
<td>25,6</td>
<td>115.000</td>
<td>1,408239965</td>
<td>5,06069784</td>
</tr>
<tr class="even">
<td>2009</td>
<td>25,7</td>
<td>120.000</td>
<td>1,409933123</td>
<td>5,079181246</td>
</tr>
<tr class="odd">
<td>2010</td>
<td>25,8</td>
<td>125.000</td>
<td>1,411619706</td>
<td>5,096910013</td>
</tr>
<tr class="even">
<td>2011</td>
<td>25,9</td>
<td>130.000</td>
<td>1,413299764</td>
<td>5,113943352</td>
</tr>
<tr class="odd">
<td>2012</td>
<td>26</td>
<td>135.000</td>
<td>1,414973348</td>
<td>5,130333768</td>
</tr>
<tr class="even">
<td>2013</td>
<td>26,1</td>
<td>140.000</td>
<td>1,416640507</td>
<td>5,146128036</td>
</tr>
<tr class="odd">
<td>2014</td>
<td>26,2</td>
<td>145.000</td>
<td>1,418301291</td>
<td>5,161368002</td>
</tr>
<tr class="even">
<td>2017</td>
<td>26,5</td>
<td>160.000</td>
<td>1,423245874</td>
<td>5,204119983</td>
</tr>
<tr class="odd">
<td>2018</td>
<td>26,6</td>
<td>165.000</td>
<td>1,424881637</td>
<td>5,217483944</td>
</tr>
<tr class="even">
<td>2019</td>
<td>26,7</td>
<td>170.000</td>
<td>1,426511261</td>
<td>5,230448921</td>
</tr>
<tr class="odd">
<td>2020</td>
<td>26,8</td>
<td>175.000</td>
<td>1,428134794</td>
<td>5,243038049</td>
</tr>
<tr class="even">
<td>2021</td>
<td>26,9</td>
<td>180.000</td>
<td>1,42975228</td>
<td>5,255272505</td>
</tr>
<tr class="odd">
<td>2022</td>
<td>27</td>
<td>318.919</td>
<td>1,431363764</td>
<td>5,503680394</td>
</tr>
</tbody>
</table>
<p>Data bersifat time series dalam kurun waktu tahun 2000 hingga 2022, dengan objek data suhu udara rata-rata dalam satuan derajat celcius dan jumlah wisatawan Bromo. Kemudian peneliti mengolah data dengan melakukan log pada kedua variabel dan mengasilkan data x dari data suhu udara dan y dari data wisatawan. Data yang telah diolah akan dijadikan sebagai objek penelitian.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">#import dataset</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>jatim<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">'jatim.xlsx'</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(jatim)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
  Tahun `Suhu Udara Rata-Rata (°C)` `Jumlah Pengunjung Bromo`     x     y
  &lt;dbl&gt;                       &lt;dbl&gt;                     &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1  2000                        24.8                     75000  1.39  4.88
2  2001                        24.9                     80000  1.40  4.90
3  2002                        25                       85000  1.40  4.93
4  2003                        25.1                     90000  1.40  4.95
5  2004                        25.2                     95000  1.40  4.98
6  2005                        25.3                    100000  1.40  5   </code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"ggplot2"</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"readxl"</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"dplyr"</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>jatim,<span class="fu">aes</span>(<span class="at">x=</span>x,<span class="at">y=</span>y))<span class="sc">+</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color=</span><span class="st">"pink"</span>,<span class="at">size=</span><span class="dv">2</span>)<span class="sc">+</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"hubunga suhu udara dan jumlah wisatawan Bromo"</span>,</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x=</span><span class="st">"suhu udara"</span>,</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y=</span><span class="st">"wisatawan"</span>,</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"sumber: Badan Pusat Statistik Kota Malang"</span>)<span class="sc">+</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="metode-analisis" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="metode-analisis"><span class="header-section-number">3.2</span> Metode analisis</h3>
<p>Dalam penelitian ini peneliti menggunakan metode regresi univariat dengan satu data independent, penelitian ini dimaksudkan untuk megetahui seberapa besar pengaruh suhu udara terhadap jumlah wisatawan bromo, dengan spesifikasi sebagai berikut:</p>
<p><span class="math display">\[
y_{t}=\beta_0 + \beta_1 x_t+\mu_t
\]</span> di mana <span class="math inline">\(y_t\)</span> adalah jumlah wisatawan dan <span class="math inline">\(x_t\)</span> adalah suhu udara.</p>
</section>
</section>
<section id="pembahasan" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="pembahasan"><span class="header-section-number">4</span> Pembahasan</h2>
<section id="pembahasan-masalah" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="pembahasan-masalah"><span class="header-section-number">4.1</span> Pembahasan masalah</h3>
<p>Rangkuman hasil:</p>
<table class="table">
<thead>
<tr class="header">
<th>Coefficients</th>
<th>Estimate</th>
<th>Pr(&gt;</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td>-11.7166</td>
<td>1.79e-09</td>
</tr>
<tr class="even">
<td>x</td>
<td>11.9065</td>
<td>2.28e-12</td>
</tr>
</tbody>
</table>
<p>Model regresi univariat dari output di atas adalah:</p>
<p><span class="math display">\[
y_{t}=\ -11.7166 + \ 11.9065x +\mu_t
\]</span></p>
<p>Hasil dari koefisien x sebesar 11.9065, yang berarti apabila x (suhu udara) naik satu, akan menyebabkan kenaikan pada y (jumlah wisatawan) sebesar 11.9065.</p>
<p>Suhu udara memiliki pengaruh positif dan signifikan terhadap jumlah wisatawan Bromo. Suhu udara di Bromo dapat mempengaruhi jumlah wisatawan yang berkunjung ke sana, tergantung pada preferensi dan tujuan wisatawan. Beberapa wisatawan mungkin lebih menyukai suhu udara yang dingin, karena dapat memberikan sensasi yang berbeda dan menantang. Beberapa wisatawan mungkin lebih menyukai suhu udara yang hangat, karena dapat memberikan kenyamanan dan keamanan. Namun mungkin saja beberapa wisatawan mungkin tidak terlalu memperhatikan suhu udara, karena lebih tertarik dengan aktivitas atau fasilitas yang ditawarkan di Bromo</p>
</section>
<section id="analisis-masalah" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="analisis-masalah"><span class="header-section-number">4.2</span> Analisis masalah</h3>
<p>Hasil regresi:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>jatim<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"jatim.xlsx"</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>reg<span class="ot">&lt;-</span><span class="fu">lm</span>(y<span class="sc">~</span>x,<span class="at">data=</span>jatim)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x, data = jatim)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.051497 -0.016727 -0.000470  0.008457  0.177724 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -11.7166     1.1665  -10.04 1.79e-09 ***
x            11.9065     0.8254   14.42 2.28e-12 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.04405 on 21 degrees of freedom
Multiple R-squared:  0.9083,    Adjusted R-squared:  0.904 
F-statistic: 208.1 on 1 and 21 DF,  p-value: 2.283e-12</code></pre>
</div>
</div>
<p>Multiple R-squared adalah ukuran seberapa baik model regresi menjelaskan variasi dari variabel dependen, nilai ini sebesar 0.9083 yang berarti bawa sekitar 90.83% variasi dari y dapat dijelaskan oleh variabel x, nilai yang tinggi menunjukkan bahhwa model ini memiliki kualitas yang baik.</p>
<p>Untuk melihat signifikansi dari keseluruhan model regresi dapat dilihat dari nilai p-value sebesar 2.283e-12, dimana nilai lebih kecil dari alpha (0.05) yang berarti model regresi secara keseluruhan signifikan.</p>
</section>
</section>
<section id="kesimpulan" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="kesimpulan"><span class="header-section-number">5</span> Kesimpulan</h2>
<p>Fluktuasi suhu udara memiliki dampak signifikan terhadap kunjungan wisatawan ke Gunung Bromo selama periode 2000 hingga 2022. Beberapa dampak yang dapat terjadi antara lain:</p>
<ol type="1">
<li><p><strong>Kelalaian wisatawan</strong>: Fluktuasi suhu udara dapat mempengaruhi kondisi cuaca, yang mungkin menyebabkan wisatawan tidak memperhatikan topografi kawasan dan kondisi cuaca, yang kemudiannya dapat menyebabkan kecelakaan wisatawan.</p></li>
<li><p><strong>Aktivitas kawah Gunung Bromo</strong>: Fluktuasi tekanan di dalam tubuh Gunung Bromo yang disertai oleh aliran fluida ke permukaan dapat meningkatkan aktivitas kawah Gunung Bromo. Potensi bahaya yang bisa ditimbulkan akibat meningkatnya aktivitas kawah Gunung Bromo adalah terjadinya erupsi freatik ataupun magmatik.</p></li>
<li><p><strong>Batasan aktivitas kunjungan</strong>: Fluktuasi suhu udara dapat menyebabkan TNBTS (Tenaga Nasional Bromo Tengger Semeru) batasi aktivitas kunjungan ke Gunung Bromo, seperti yang terjadi pada 2023-12-14.</p></li>
</ol>
<p>Dalam hal ini, perlu diingat bahwa fluktuasi suhu udara hanya salah satu faktor yang mempengaruhi keselamatan dan kenyamanan wisatawan di Gunung Bromo. Selain itu, perlu dipertimbangkan faktor lain seperti topografi kawasan, kondisi cuaca, dan aktivitas kawah Gunung Bromo.</p>
</section>
<section id="referensi" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="referensi"><span class="header-section-number">6</span> Referensi</h2>
<p>Wibowo, J. M., Muljaningsih, S., &amp; Satria, D. (2021). DAYA SAING EKOWISATA BERKELANJUTAN TAMAN NASIONAL BROMO TENGGER SEMERU. Jurnal Penelitian Sosial dan Ekonomi Kehutanan Vol, 18(1), 45-62.</p>
<p>Noorsy, H. F., Suprapta, B., &amp; Ridhoi, R. (2022). Erupsi Gunung Bromo 1995: kajian dampak dan upaya mitigasinya di Kecamatan Sukapura. 2.</p>
<p>Amalia, T., Ekwarso, H., &amp; Taryono, T. (2017). Pengaruh Lingkungan Fisik Terhadap Tingkat Kunjungan Wisatawan Di Museum Daerah Sang Nila Utama Kota Pekanbaru (Doctoral dissertation, Riau University).</p>
<p>Kristina, Y., &amp; Rohman, A. (2020). pengaruh pengembangan sarana prasarana wisata terhadap peningkatan jumlah wisatawan (Doctoral dissertation, Fakultas Ilmu Sosial dan Ilmu Politik Universitas Tribhuwana Tungga Dewi Malang).</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>